export const kantoPokemon = [
    "Bulbasaur - Male",
    "Bulbasaur - Female",
    "Ivysaur - Male",
    "Ivysaur - Female",
    "Venusaur - Male",
    "Venusaur - Female",
    "Charmander - Male",
    "Charmander - Female",
    "Charmeleon - Male",
    "Charmeleon - Female",
    "Charizard - Male",
    "Charizard - Female",
    "Squirtle - Male",
    "Squirtle - Female",
    "Wartortle - Male",
    "Wartortle - Female",
    "Blastoise - Male",
    "Blastoise - Female",
    "Caterpie - Male",
    "Caterpie - Female",
    "Metapod - Male",
    "Metapod - Female",
    "Butterfree - Male",
    "Butterfree - Female",
    "Weedle - Male",
    "Weedle - Female",
    "Kakuna - Male",
    "Kakuna - Female",
    "Beedrill - Male",
    "Beedrill - Female",
    "Pidgey - Male",
    "Pidgey - Female",
    "Pidgeotto - Male",
    "Pidgeotto - Female",
    "Pidgeot - Male",
    "Pidgeot - Female",
    "Rattata - Male",
    "Rattata - Female",
    "Raticate - Male",
    "Raticate - Female",
    "Spearow - Male",
    "Spearow - Female",
    "Fearow - Male",
    "Fearow - Female",
    "Ekans - Male",
    "Ekans - Female",
    "Arbok - Male",
    "Arbok - Female",
    "Pikachu - Male",
    "Pikachu - Female",
    "Cap Pikachu - Original",
    "Cap Pikachu - Kalos",
    "Cap Pikachu - Hoenn",
    "Cap Pikachu - Sinnoh",
    "Cap Pikachu - Unova",
    "Cap Pikachu - Alola",
    "Cap Pikachu - Partner",
    "Cap Pikachu - World",
    "Raichu - Male",
    "Raichu - Female",
    "Sandshrew - Male",
    "Sandshrew - Female",
    "Sandslash - Male",
    "Sandslash - Female",
    "Nidoran F - Female",
    "Nidorina - Female",
    "Nidoqueen - Female",
    "Nidoran M - Male",
    "Nidorino - Male",
    "Nidoking - Male",
    "Clefairy - Male",
    "Clefairy - Female",
    "Clefable - Male",
    "Clefable - Female",
    "Vulpix - Male",
    "Vulpix - Female",
    "Ninetales - Male",
    "Ninetales - Female",
    "Jigglypuff - Male",
    "Jigglypuff - Female",
    "Wigglytuff - Male",
    "Wigglytuff - Female",
    "Zubat - Male",
    "Zubat - Female",
    "Golbat - Male",
    "Golbat - Female",
    "Oddish - Male",
    "Oddish - Female",
    "Gloom - Male",
    "Gloom - Female",
    "Vileplume - Male",
    "Vileplume - Female",
    "Paras - Male",
    "Paras - Female",
    "Parasect - Male",
    "Parasect - Female",
    "Venonat - Male",
    "Venonat - Female",
    "Venomoth - Male",
    "Venomoth - Female",
    "Diglett - Male",
    "Diglett - Female",
    "Dugtrio - Male",
    "Dugtrio - Female",
    "Meowth - Male",
    "Meowth - Female",
    "Persian - Male",
    "Persian - Female",
    "Psyduck - Male",
    "Psyduck - Female",
    "Golduck - Male",
    "Golduck - Female",
    "Mankey - Male",
    "Mankey - Female",
    "Primeape - Male",
    "Primeape - Female",
    "Growlithe - Male",
    "Growlithe - Female",
    "Arcanine - Male",
    "Arcanine - Female",
    "Poliwag - Male",
    "Poliwag - Female",
    "Poliwhirl - Male",
    "Poliwhirl - Female",
    "Poliwrath - Male",
    "Poliwrath - Female",
    "Abra - Male",
    "Abra - Female",
    "Kadabra - Male",
    "Kadabra - Female",
    "Alakazam - Male",
    "Alakazam - Female",
    "Machop - Male",
    "Machop - Female",
    "Machoke - Male",
    "Machoke - Female",
    "Machamp - Male",
    "Machamp - Female",
    "Bellsprout - Male",
    "Bellsprout - Female",
    "Weepinbell - Male",
    "Weepinbell - Female",
    "Victreebel - Male",
    "Victreebel - Female",
    "Tentacool - Male",
    "Tentacool - Female",
    "Tentacruel - Male",
    "Tentacruel - Female",
    "Geodude - Male",
    "Geodude - Female",
    "Graveler - Male",
    "Graveler - Female",
    "Golem - Male",
    "Golem - Female",
    "Ponyta - Male",
    "Ponyta - Female",
    "Rapidash - Male",
    "Rapidash - Female",
    "Slowpoke - Male",
    "Slowpoke - Female",
    "Slowbro - Male",
    "Slowbro - Female",
    "Magnemite - Genderless",
    "Magneton - Genderless",
    "Farfetch'd - Male",
    "Farfetch'd - Female",
    "Doduo - Male",
    "Doduo - Female",
    "Dodrio - Male",
    "Dodrio - Female",
    "Seel - Male",
    "Seel - Female",
    "Dewgong - Male",
    "Dewgong - Female",
    "Grimer - Male",
    "Grimer - Female",
    "Muk - Male",
    "Muk - Female",
    "Shellder - Male",
    "Shellder - Female",
    "Cloyster - Male",
    "Cloyster - Female",
    "Gastly - Male",
    "Gastly - Female",
    "Haunter - Male",
    "Haunter - Female",
    "Gengar - Male",
    "Gengar - Female",
    "Onix - Male",
    "Onix - Female",
    "Drowzee - Male",
    "Drowzee - Female",
    "Hypno - Male",
    "Hypno - Female",
    "Krabby - Male",
    "Krabby - Female",
    "Kingler - Male",
    "Kingler - Female",
    "Voltorb - Genderless",
    "Electrode - Genderless",
    "Exeggcute - Male",
    "Exeggcute - Female",
    "Exeggutor - Male",
    "Exeggutor - Female",
    "Cubone - Male",
    "Cubone - Female",
    "Marowak - Male",
    "Marowak - Female",
    "Hitmonlee - Male",
    "Hitmonchan - Male",
    "Lickitung - Male",
    "Lickitung - Female",
    "Koffing - Male",
    "Koffing - Female",
    "Weezing - Male",
    "Weezing - Female",
    "Rhyhorn - Male",
    "Rhyhorn - Female",
    "Rhydon - Male",
    "Rhydon - Female",
    "Chansey - Female",
    "Tangela - Male",
    "Tangela - Female",
    "Kangaskhan - Female",
    "Horsea - Male",
    "Horsea - Female",
    "Seadra - Male",
    "Seadra - Female",
    "Goldeen - Male",
    "Goldeen - Female",
    "Seaking - Male",
    "Seaking - Female",
    "Staryu - Genderless",
    "Starmie - Genderless",
    "Mr. Mime - Male",
    "Mr. Mime - Female",
    "Scyther - Male",
    "Scyther - Female",
    "Jynx - Female",
    "Electabuzz - Male",
    "Electabuzz - Female",
    "Magmar - Male",
    "Magmar - Female",
    "Pinsir - Male",
    "Pinsir - Female",
    "Tauros - Male",
    "Magikarp - Male",
    "Magikarp - Female",
    "Gyarados - Male",
    "Gyarados - Female",
    "Lapras - Male",
    "Lapras - Female",
    "Ditto - Genderless",
    "Eevee - Male",
    "Eevee - Female",
    "Vaporeon - Male",
    "Vaporeon - Female",
    "Jolteon - Male",
    "Jolteon - Female",
    "Flareon - Male",
    "Flareon - Female",
    "Porygon - Genderless",
    "Omanyte - Male",
    "Omanyte - Female",
    "Omastar - Male",
    "Omastar - Female",
    "Kabuto - Male",
    "Kabuto - Female",
    "Kabutops - Male",
    "Kabutops - Female",
    "Aerodactyl - Male",
    "Aerodactyl - Female",
    "Snorlax - Male",
    "Snorlax - Female",
    "Articuno - Genderless",
    "Zapdos - Genderless",
    "Moltres - Genderless",
    "Dratini - Male",
    "Dratini - Female",
    "Dragonair - Male",
    "Dragonair - Female",
    "Dragonite - Male",
    "Dragonite - Female",
    "Mewtwo - Genderless",
    "Mew - Genderless"
];

export const johtoPokemon = [
    "Chikorita - Male",
    "Chikorita - Female",
    "Bayleef - Male",
    "Bayleef - Female",
    "Meganium - Male",
    "Meganium - Female",
    "Cyndaquil - Male",
    "Cyndaquil - Female",
    "Quilava - Male",
    "Quilava - Female",
    "Typhlosion - Male",
    "Typhlosion - Female",
    "Totodile - Male",
    "Totodile - Female",
    "Croconaw - Male",
    "Croconaw - Female",
    "Feraligatr - Male",
    "Feraligatr - Female",
    "Sentret - Male",
    "Sentret - Female",
    "Furret - Male",
    "Furret - Female",
    "Hoothoot - Male",
    "Hoothoot - Female",
    "Noctowl - Male",
    "Noctowl - Female",
    "Ledyba - Male",
    "Ledyba - Female",
    "Ledian - Male",
    "Ledian - Female",
    "Spinarak - Male",
    "Spinarak - Female",
    "Ariados - Male",
    "Ariados - Female",
    "Crobat - Male",
    "Crobat - Female",
    "Chinchou - Male",
    "Chinchou - Female",
    "Lanturn - Male",
    "Lanturn - Female",
    "Pichu - Male",
    "Pichu - Female",
    "Cleffa - Male",
    "Cleffa - Female",
    "Igglybuff - Male",
    "Igglybuff - Female",
    "Togepi - Male",
    "Togepi - Female",
    "Togetic - Male",
    "Togetic - Female",
    "Natu - Male",
    "Natu - Female",
    "Xatu - Male",
    "Xatu - Female",
    "Mareep - Male",
    "Mareep - Female",
    "Flaaffy - Male",
    "Flaaffy - Female",
    "Ampharos - Male",
    "Ampharos - Female",
    "Bellossom - Male",
    "Bellossom - Female",
    "Marill - Male",
    "Marill - Female",
    "Azumarill - Male",
    "Azumarill - Female",
    "Sudowoodo - Male",
    "Sudowoodo - Female",
    "Politoed - Male",
    "Politoed - Female",
    "Hoppip - Male",
    "Hoppip - Female",
    "Skiploom - Male",
    "Skiploom - Female",
    "Jumpluff - Male",
    "Jumpluff - Female",
    "Aipom - Male",
    "Aipom - Female",
    "Sunkern - Male",
    "Sunkern - Female",
    "Sunflora - Male",
    "Sunflora - Female",
    "Yanma - Male",
    "Yanma - Female",
    "Wooper - Male",
    "Wooper - Female",
    "Quagsire - Male",
    "Quagsire - Female",
    "Espeon - Male",
    "Espeon - Female",
    "Umbreon - Male",
    "Umbreon - Female",
    "Murkrow - Male",
    "Murkrow - Female",
    "Slowking - Male",
    "Slowking - Female",
    "Misdreavus - Male",
    "Misdreavus - Female",
    "Unown - A - Genderless",
    "Unown - B - Genderless",
    "Unown - C - Genderless",
    "Unown - D - Genderless",
    "Unown - E - Genderless",
    "Unown - F - Genderless",
    "Unown - G - Genderless",
    "Unown - H - Genderless",
    "Unown - I - Genderless",
    "Unown - J - Genderless",
    "Unown - K - Genderless",
    "Unown - L - Genderless",
    "Unown - M - Genderless",
    "Unown - N - Genderless",
    "Unown - O - Genderless",
    "Unown - P - Genderless",
    "Unown - Q - Genderless",
    "Unown - R - Genderless",
    "Unown - S - Genderless",
    "Unown - T - Genderless",
    "Unown - U - Genderless",
    "Unown - V - Genderless",
    "Unown - W - Genderless",
    "Unown - X - Genderless",
    "Unown - Y - Genderless",
    "Unown - Z - Genderless",
    "Unown - Exclamation - Genderless",
    "Unown - Question - Genderless",
    "Wobbuffet - Male",
    "Wobbuffet - Female",
    "Girafarig - Male",
    "Girafarig - Female",
    "Pineco - Male",
    "Pineco - Female",
    "Forretress - Male",
    "Forretress - Female",
    "Dunsparce - Male",
    "Dunsparce - Female",
    "Gligar - Male",
    "Gligar - Female",
    "Steelix - Male",
    "Steelix - Female",
    "Snubbull - Male",
    "Snubbull - Female",
    "Granbull - Male",
    "Granbull - Female",
    "Qwilfish - Male",
    "Qwilfish - Female",
    "Scizor - Male",
    "Scizor - Female",
    "Shuckle - Male",
    "Shuckle - Female",
    "Heracross - Male",
    "Heracross - Female",
    "Sneasel - Male",
    "Sneasel - Female",
    "Teddiursa - Male",
    "Teddiursa - Female",
    "Ursaring - Male",
    "Ursaring - Female",
    "Slugma - Male",
    "Slugma - Female",
    "Magcargo - Male",
    "Magcargo - Female",
    "Swinub - Male",
    "Swinub - Female",
    "Piloswine - Male",
    "Piloswine - Female",
    "Corsola - Male",
    "Corsola - Female",
    "Remoraid - Male",
    "Remoraid - Female",
    "Octillery - Male",
    "Octillery - Female",
    "Delibird - Male",
    "Delibird - Female",
    "Mantine - Male",
    "Mantine - Female",
    "Skarmory - Male",
    "Skarmory - Female",
    "Houndour - Male",
    "Houndour - Female",
    "Houndoom - Male",
    "Houndoom - Female",
    "Kingdra - Male",
    "Kingdra - Female",
    "Phanpy - Male",
    "Phanpy - Female",
    "Donphan - Male",
    "Donphan - Female",
    "Porygon2 - Genderless",
    "Stantler - Male",
    "Stantler - Female",
    "Smeargle - Male",
    "Smeargle - Female",
    "Tyrogue - Male",
    "Hitmontop - Male",
    "Smoochum - Female",
    "Elekid - Male",
    "Elekid - Female",
    "Magby - Male",
    "Magby - Female",
    "Miltank - Female",
    "Blissey - Female",
    "Raikou - Genderless",
    "Entei - Genderless",
    "Suicune - Genderless",
    "Larvitar - Male",
    "Larvitar - Female",
    "Pupitar - Male",
    "Pupitar - Female",
    "Tyranitar - Male",
    "Tyranitar - Female",
    "Lugia - Genderless",
    "Ho-Oh - Genderless",
    "Celebi - Genderless"
];

export const hoennPokemon = [
    "Treecko - Male",
    "Treecko - Female",
    "Grovyle - Male",
    "Grovyle - Female",
    "Sceptile - Male",
    "Sceptile - Female",
    "Torchic - Male",
    "Torchic - Female",
    "Combusken - Male",
    "Combusken - Female",
    "Blaziken - Male",
    "Blaziken - Female",
    "Mudkip - Male",
    "Mudkip - Female",
    "Marshtomp - Male",
    "Marshtomp - Female",
    "Swampert - Male",
    "Swampert - Female",
    "Poochyena - Male",
    "Poochyena - Female",
    "Mightyena - Male",
    "Mightyena - Female",
    "Zigzagoon - Male",
    "Zigzagoon - Female",
    "Linoone - Male",
    "Linoone - Female",
    "Wurmple - Male",
    "Wurmple - Female",
    "Silcoon - Male",
    "Silcoon - Female",
    "Beautifly - Male",
    "Beautifly - Female",
    "Cascoon - Male",
    "Cascoon - Female",
    "Dustox - Male",
    "Dustox - Female",
    "Lotad - Male",
    "Lotad - Female",
    "Lombre - Male",
    "Lombre - Female",
    "Ludicolo - Male",
    "Ludicolo - Female",
    "Seedot - Male",
    "Seedot - Female",
    "Nuzleaf - Male",
    "Nuzleaf - Female",
    "Shiftry - Male",
    "Shiftry - Female",
    "Taillow - Male",
    "Taillow - Female",
    "Swellow - Male",
    "Swellow - Female",
    "Wingull - Male",
    "Wingull - Female",
    "Pelipper - Male",
    "Pelipper - Female",
    "Ralts - Male",
    "Ralts - Female",
    "Kirlia - Male",
    "Kirlia - Female",
    "Gardevoir - Male",
    "Gardevoir - Female",
    "Surskit - Male",
    "Surskit - Female",
    "Masquerain - Male",
    "Masquerain - Female",
    "Shroomish - Male",
    "Shroomish - Female",
    "Breloom - Male",
    "Breloom - Female",
    "Slakoth - Male",
    "Slakoth - Female",
    "Vigoroth - Male",
    "Vigoroth - Female",
    "Slaking - Male",
    "Slaking - Female",
    "Nincada - Male",
    "Nincada - Female",
    "Ninjask - Male",
    "Ninjask - Female",
    "Shedinja - Genderless",
    "Whismur - Male",
    "Whismur - Female",
    "Loudred - Male",
    "Loudred - Female",
    "Exploud - Male",
    "Exploud - Female",
    "Makuhita - Male",
    "Makuhita - Female",
    "Hariyama - Male",
    "Hariyama - Female",
    "Azurill - Male",
    "Azurill - Female",
    "Nosepass - Male",
    "Nosepass - Female",
    "Skitty - Male",
    "Skitty - Female",
    "Delcatty - Male",
    "Delcatty - Female",
    "Sableye - Male",
    "Sableye - Female",
    "Mawile - Male",
    "Mawile - Female",
    "Aron - Male",
    "Aron - Female",
    "Lairon - Male",
    "Lairon - Female",
    "Aggron - Male",
    "Aggron - Female",
    "Meditite - Male",
    "Meditite - Female",
    "Medicham - Male",
    "Medicham - Female",
    "Electrike - Male",
    "Electrike - Female",
    "Manectric - Male",
    "Manectric - Female",
    "Plusle - Male",
    "Plusle - Female",
    "Minun - Male",
    "Minun - Female",
    "Volbeat - Male",
    "Illumise - Female",
    "Roselia - Male",
    "Roselia - Female",
    "Gulpin - Male",
    "Gulpin - Female",
    "Swalot - Male",
    "Swalot - Female",
    "Carvanha - Male",
    "Carvanha - Female",
    "Sharpedo - Male",
    "Sharpedo - Female",
    "Wailmer - Male",
    "Wailmer - Female",
    "Wailord - Male",
    "Wailord - Female",
    "Numel - Male",
    "Numel - Female",
    "Camerupt - Male",
    "Camerupt - Female",
    "Torkoal - Male",
    "Torkoal - Female",
    "Spoink - Male",
    "Spoink - Female",
    "Grumpig - Male",
    "Grumpig - Female",
    "Spinda - Male",
    "Spinda - Female",
    "Trapinch - Male",
    "Trapinch - Female",
    "Vibrava - Male",
    "Vibrava - Female",
    "Flygon - Male",
    "Flygon - Female",
    "Cacnea - Male",
    "Cacnea - Female",
    "Cacturne - Male",
    "Cacturne - Female",
    "Swablu - Male",
    "Swablu - Female",
    "Altaria - Male",
    "Altaria - Female",
    "Zangoose - Male",
    "Zangoose - Female",
    "Seviper - Male",
    "Seviper - Female",
    "Lunatone - Genderless",
    "Solrock - Genderless",
    "Barboach - Male",
    "Barboach - Female",
    "Whiscash - Male",
    "Whiscash - Female",
    "Corphish - Male",
    "Corphish - Female",
    "Crawdaunt - Male",
    "Crawdaunt - Female",
    "Baltoy - Genderless",
    "Claydol - Genderless",
    "Lileep - Male",
    "Lileep - Female",
    "Cradily - Male",
    "Cradily - Female",
    "Anorith - Male",
    "Anorith - Female",
    "Armaldo - Male",
    "Armaldo - Female",
    "Feebas - Male",
    "Feebas - Female",
    "Milotic - Male",
    "Milotic - Female",
    "Castform - Male",
    "Castform - Female",
    "Kecleon - Male",
    "Kecleon - Female",
    "Shuppet - Male",
    "Shuppet - Female",
    "Banette - Male",
    "Banette - Female",
    "Duskull - Male",
    "Duskull - Female",
    "Dusclops - Male",
    "Dusclops - Female",
    "Tropius - Male",
    "Tropius - Female",
    "Chimecho - Male",
    "Chimecho - Female",
    "Absol - Male",
    "Absol - Female",
    "Wynaut - Male",
    "Wynaut - Female",
    "Snorunt - Male",
    "Snorunt - Female",
    "Glalie - Male",
    "Glalie - Female",
    "Spheal - Male",
    "Spheal - Female",
    "Sealeo - Male",
    "Sealeo - Female",
    "Walrein - Male",
    "Walrein - Female",
    "Clamperl - Male",
    "Clamperl - Female",
    "Huntail - Male",
    "Huntail - Female",
    "Gorebyss - Male",
    "Gorebyss - Female",
    "Relicanth - Male",
    "Relicanth - Female",
    "Luvdisc - Male",
    "Luvdisc - Female",
    "Bagon - Male",
    "Bagon - Female",
    "Shelgon - Male",
    "Shelgon - Female",
    "Salamence - Male",
    "Salamence - Female",
    "Beldum - Genderless",
    "Metang - Genderless",
    "Metagross - Genderless",
    "Regirock - Genderless",
    "Regice - Genderless",
    "Registeel - Genderless",
    "Latias - Female",
    "Latios - Male",
    "Kyogre - Genderless",
    "Groudon - Genderless",
    "Rayquaza - Genderless",
    "Jirachi - Genderless",
    "Deoxys - Genderless",
    "Deoxys - Attack - Genderless",
    "Deoxys - Defense - Genderless",
    "Deoxys - Speed - Genderless"
];

export const sinnohPokemon = [
    "Turtwig - Male",
    "Turtwig - Female",
    "Grotle - Male",
    "Grotle - Female",
    "Torterra - Male",
    "Torterra - Female",
    "Chimchar - Male",
    "Chimchar - Female",
    "Monferno - Male",
    "Monferno - Female",
    "Infernape - Male",
    "Infernape - Female",
    "Piplup - Male",
    "Piplup - Female",
    "Prinplup - Male",
    "Prinplup - Female",
    "Empoleon - Male",
    "Empoleon - Female",
    "Starly - Male",
    "Starly - Female",
    "Staravia - Male",
    "Staravia - Female",
    "Staraptor - Male",
    "Staraptor - Female",
    "Bidoof - Male",
    "Bidoof - Female",
    "Bibarel - Male",
    "Bibarel - Female",
    "Kricketot - Male",
    "Kricketot - Female",
    "Kricketune - Male",
    "Kricketune - Female",
    "Shinx - Male",
    "Shinx - Female",
    "Luxio - Male",
    "Luxio - Female",
    "Luxray - Male",
    "Luxray - Female",
    "Budew - Male",
    "Budew - Female",
    "Roserade - Male",
    "Roserade - Female",
    "Cranidos - Male",
    "Cranidos - Female",
    "Rampardos - Male",
    "Rampardos - Female",
    "Shieldon - Male",
    "Shieldon - Female",
    "Bastiodon - Male",
    "Bastiodon - Female",
    "Burmy - Plant - Male",
    "Burmy - Plant - Female",
    "Burmy - Sandy - Male",
    "Burmy - Sandy - Female",
    "Burmy - Trash - Male",
    "Burmy - Trash - Female",
    "Wormadam - Plant - Female",
    "Wormadam - Sandy - Female",
    "Wormadam - Trash - Female",
    "Mothim - Male",
    "Combee - Male",
    "Combee - Female",
    "Vespiquen - Female",
    "Pachirisu - Male",
    "Pachirisu - Female",
    "Buizel - Male",
    "Buizel - Female",
    "Floatzel - Male",
    "Floatzel - Female",
    "Cherubi - Male",
    "Cherubi - Female",
    "Cherrim - Male",
    "Cherrim - Female",
    "Shellos - West Sea - Male",
    "Shellos - West Sea - Female",
    "Shellos - East Sea - Male",
    "Shellos - East Sea - Female",
    "Gastrodon - West Sea - Male",
    "Gastrodon - West Sea - Female",
    "Gastrodon - East Sea - Male",
    "Gastrodon - East Sea - Female",
    "Ambipom - Male",
    "Ambipom - Female",
    "Drifloon - Male",
    "Drifloon - Female",
    "Drifblim - Male",
    "Drifblim - Female",
    "Buneary - Male",
    "Buneary - Female",
    "Lopunny - Male",
    "Lopunny - Female",
    "Mismagius - Male",
    "Mismagius - Female",
    "Honchkrow - Male",
    "Honchkrow - Female",
    "Glameow - Male",
    "Glameow - Female",
    "Purugly - Male",
    "Purugly - Female",
    "Chingling - Male",
    "Chingling - Female",
    "Stunky - Male",
    "Stunky - Female",
    "Skuntank - Male",
    "Skuntank - Female",
    "Bronzor - Genderless",
    "Bronzong - Genderless",
    "Bonsly - Male",
    "Bonsly - Female",
    "Mime Jr. - Male",
    "Mime Jr. - Female",
    "Happiny - Female",
    "Chatot - Male",
    "Chatot - Female",
    "Spiritomb - Male",
    "Spiritomb - Female",
    "Gible - Male",
    "Gible - Female",
    "Gabite - Male",
    "Gabite - Female",
    "Garchomp - Male",
    "Garchomp - Female",
    "Munchlax - Male",
    "Munchlax - Female",
    "Riolu - Male",
    "Riolu - Female",
    "Lucario - Male",
    "Lucario - Female",
    "Hippopotas - Male",
    "Hippopotas - Female",
    "Hippowdon - Male",
    "Hippowdon - Female",
    "Skorupi - Male",
    "Skorupi - Female",
    "Drapion - Male",
    "Drapion - Female",
    "Croagunk - Male",
    "Croagunk - Female",
    "Toxicroak - Male",
    "Toxicroak - Female",
    "Carnivine - Male",
    "Carnivine - Female",
    "Finneon - Male",
    "Finneon - Female",
    "Lumineon - Male",
    "Lumineon - Female",
    "Mantyke - Male",
    "Mantyke - Female",
    "Snover - Male",
    "Snover - Female",
    "Abomasnow - Male",
    "Abomasnow - Female",
    "Weavile - Male",
    "Weavile - Female",
    "Magnezone - Genderless",
    "Lickilicky - Male",
    "Lickilicky - Female",
    "Rhyperior - Male",
    "Rhyperior - Female",
    "Tangrowth - Male",
    "Tangrowth - Female",
    "Electivire - Male",
    "Electivire - Female",
    "Magmortar - Male",
    "Magmortar - Female",
    "Togekiss - Male",
    "Togekiss - Female",
    "Yanmega - Male",
    "Yanmega - Female",
    "Leafeon - Male",
    "Leafeon - Female",
    "Glaceon - Male",
    "Glaceon - Female",
    "Gliscor - Male",
    "Gliscor - Female",
    "Mamoswine - Male",
    "Mamoswine - Female",
    "Porygon-Z - Genderless",
    "Gallade - Male",
    "Probopass - Male",
    "Probopass - Female",
    "Dusknoir - Male",
    "Dusknoir - Female",
    "Froslass - Female",
    "Rotom - Genderless",
    "Rotom - Heat - Genderless",
    "Rotom - Wash - Genderless",
    "Rotom - Frost - Genderless",
    "Rotom - Fan - Genderless",
    "Rotom - Mow - Genderless",
    "Uxie - Genderless",
    "Mesprit - Genderless",
    "Azelf - Genderless",
    "Dialga - Genderless",
    "Palkia - Genderless",
    "Heatran - Male",
    "Heatran - Female",
    "Regigigas - Genderless",
    "Giratina - Genderless",
    "Cresselia - Female",
    "Phione - Genderless",
    "Manaphy - Genderless",
    "Darkrai - Genderless",
    "Shaymin - Genderless",
    "Shaymin - Sky Form - Genderless",
    "Arceus - Genderless"
];

export const unovaPokemon = [
    "Victini - Genderless",
    "Snivy - Male",
    "Snivy - Female",
    "Servine - Male",
    "Servine - Female",
    "Serperior - Male",
    "Serperior - Female",
    "Tepig - Male",
    "Tepig - Female",
    "Pignite - Male",
    "Pignite - Female",
    "Emboar - Male",
    "Emboar - Female",
    "Oshawott - Male",
    "Oshawott - Female",
    "Dewott - Male",
    "Dewott - Female",
    "Samurott - Male",
    "Samurott - Female",
    "Patrat - Male",
    "Patrat - Female",
    "Watchog - Male",
    "Watchog - Female",
    "Lillipup - Male",
    "Lillipup - Female",
    "Herdier - Male",
    "Herdier - Female",
    "Stoutland - Male",
    "Stoutland - Female",
    "Purrloin - Male",
    "Purrloin - Female",
    "Liepard - Male",
    "Liepard - Female",
    "Pansage - Male",
    "Pansage - Female",
    "Simisage - Male",
    "Simisage - Female",
    "Pansear - Male",
    "Pansear - Female",
    "Simisear - Male",
    "Simisear - Female",
    "Panpour - Male",
    "Panpour - Female",
    "Simipour - Male",
    "Simipour - Female",
    "Munna - Male",
    "Munna - Female",
    "Musharna - Male",
    "Musharna - Female",
    "Pidove - Male",
    "Pidove - Female",
    "Tranquill - Male",
    "Tranquill - Female",
    "Unfezant - Male",
    "Unfezant - Female",
    "Blitzle - Male",
    "Blitzle - Female",
    "Zebstrika - Male",
    "Zebstrika - Female",
    "Roggenrola - Male",
    "Roggenrola - Female",
    "Boldore - Male",
    "Boldore - Female",
    "Gigalith - Male",
    "Gigalith - Female",
    "Woobat - Male",
    "Woobat - Female",
    "Swoobat - Male",
    "Swoobat - Female",
    "Drilbur - Male",
    "Drilbur - Female",
    "Excadrill - Male",
    "Excadrill - Female",
    "Audino - Male",
    "Audino - Female",
    "Timburr - Male",
    "Timburr - Female",
    "Gurdurr - Male",
    "Gurdurr - Female",
    "Conkeldurr - Male",
    "Conkeldurr - Female",
    "Tympole - Male",
    "Tympole - Female",
    "Palpitoad - Male",
    "Palpitoad - Female",
    "Seismitoad - Male",
    "Seismitoad - Female",
    "Throh - Male",
    "Sawk - Male",
    "Sewaddle - Male",
    "Sewaddle - Female",
    "Swadloon - Male",
    "Swadloon - Female",
    "Leavanny - Male",
    "Leavanny - Female",
    "Venipede - Male",
    "Venipede - Female",
    "Whirlipede - Male",
    "Whirlipede - Female",
    "Scolipede - Male",
    "Scolipede - Female",
    "Cottonee - Male",
    "Cottonee - Female",
    "Whimsicott - Male",
    "Whimsicott - Female",
    "Petilil - Female",
    "Lilligant - Female",
    "Basculin - Red - Male",
    "Basculin - Red - Female",
    "Basculin - Blue - Male",
    "Basculin - Blue - Female",
    "Sandile - Male",
    "Sandile - Female",
    "Krokorok - Male",
    "Krokorok - Female",
    "Krookodile - Male",
    "Krookodile - Female",
    "Darumaka - Male",
    "Darumaka - Female",
    "Darmanitan - Male",
    "Darmanitan - Female",
    "Maractus - Male",
    "Maractus - Female",
    "Dwebble - Male",
    "Dwebble - Female",
    "Crustle - Male",
    "Crustle - Female",
    "Scraggy - Male",
    "Scraggy - Female",
    "Scrafty - Male",
    "Scrafty - Female",
    "Sigilyph - Male",
    "Sigilyph - Female",
    "Yamask - Male",
    "Yamask - Female",
    "Cofagrigus - Male",
    "Cofagrigus - Female",
    "Tirtouga - Male",
    "Tirtouga - Female",
    "Carracosta - Male",
    "Carracosta - Female",
    "Archen - Male",
    "Archen - Female",
    "Archeops - Male",
    "Archeops - Female",
    "Trubbish - Male",
    "Trubbish - Female",
    "Garbodor - Male",
    "Garbodor - Female",
    "Zorua - Male",
    "Zorua - Female",
    "Zoroark - Male",
    "Zoroark - Female",
    "Minccino - Male",
    "Minccino - Female",
    "Cinccino - Male",
    "Cinccino - Female",
    "Gothita - Male",
    "Gothita - Female",
    "Gothorita - Male",
    "Gothorita - Female",
    "Gothitelle - Male",
    "Gothitelle - Female",
    "Solosis - Male",
    "Solosis - Female",
    "Duosion - Male",
    "Duosion - Female",
    "Reuniclus - Male",
    "Reuniclus - Female",
    "Ducklett - Male",
    "Ducklett - Female",
    "Swanna - Male",
    "Swanna - Female",
    "Vanillite - Male",
    "Vanillite - Female",
    "Vanillish - Male",
    "Vanillish - Female",
    "Vanilluxe - Male",
    "Vanilluxe - Female",
    "Deerling - Summer - Male",
    "Deerling - Summer - Female",
    "Deerling - Autumn - Male",
    "Deerling - Autumn - Female",
    "Deerling - Winter - Male",
    "Deerling - Winter - Female",
    "Deerling - Spring - Male",
    "Deerling - Spring - Female",
    "Sawsbuck - Summer - Male",
    "Sawsbuck - Summer - Female",
    "Sawsbuck - Autumn - Male",
    "Sawsbuck - Autumn - Female",
    "Sawsbuck - Winter - Male",
    "Sawsbuck - Winter - Female",
    "Sawsbuck - Spring - Male",
    "Sawsbuck - Spring - Female",
    "Emolga - Male",
    "Emolga - Female",
    "Karrablast - Male",
    "Karrablast - Female",
    "Escavalier - Male",
    "Escavalier - Female",
    "Foongus - Male",
    "Foongus - Female",
    "Amoonguss - Male",
    "Amoonguss - Female",
    "Frillish - Male",
    "Frillish - Female",
    "Jellicent - Male",
    "Jellicent - Female",
    "Alomomola - Male",
    "Alomomola - Female",
    "Joltik - Male",
    "Joltik - Female",
    "Galvantula - Male",
    "Galvantula - Female",
    "Ferroseed - Male",
    "Ferroseed - Female",
    "Ferrothorn - Male",
    "Ferrothorn - Female",
    "Klink - Genderless",
    "Klang - Genderless",
    "Klinklang - Genderless",
    "Tynamo - Male",
    "Tynamo - Female",
    "Eelektrik - Male",
    "Eelektrik - Female",
    "Eelektross - Male",
    "Eelektross - Female",
    "Elgyem - Male",
    "Elgyem - Female",
    "Beheeyem - Male",
    "Beheeyem - Female",
    "Litwick - Male",
    "Litwick - Female",
    "Lampent - Male",
    "Lampent - Female",
    "Chandelure - Male",
    "Chandelure - Female",
    "Axew - Male",
    "Axew - Female",
    "Fraxure - Male",
    "Fraxure - Female",
    "Haxorus - Male",
    "Haxorus - Female",
    "Cubchoo - Male",
    "Cubchoo - Female",
    "Beartic - Male",
    "Beartic - Female",
    "Cryogonal - Genderless",
    "Shelmet - Male",
    "Shelmet - Female",
    "Accelgor - Male",
    "Accelgor - Female",
    "Stunfisk - Male",
    "Stunfisk - Female",
    "Mienfoo - Male",
    "Mienfoo - Female",
    "Mienshao - Male",
    "Mienshao - Female",
    "Druddigon - Male",
    "Druddigon - Female",
    "Golett - Genderless",
    "Golurk - Genderless",
    "Pawniard - Male",
    "Pawniard - Female",
    "Bisharp - Male",
    "Bisharp - Female",
    "Bouffalant - Male",
    "Bouffalant - Female",
    "Rufflet - Male",
    "Braviary - Male",
    "Vullaby - Female",
    "Mandibuzz - Female",
    "Heatmor - Male",
    "Heatmor - Female",
    "Durant - Male",
    "Durant - Female",
    "Deino - Male",
    "Deino - Female",
    "Zweilous - Male",
    "Zweilous - Female",
    "Hydreigon - Male",
    "Hydreigon - Female",
    "Larvesta - Male",
    "Larvesta - Female",
    "Volcarona - Male",
    "Volcarona - Female",
    "Cobalion - Genderless",
    "Terrakion - Genderless",
    "Virizion - Genderless",
    "Tornadus - Male",
    "Tornadus - Therian - Male",
    "Thundurus - Male",
    "Thundurus - Therian - Male",
    "Reshiram - Genderless",
    "Zekrom - Genderless",
    "Landorus - Male",
    "Landorus - Therian - Male",
    "Kyurem - Genderless",
    "Keldeo - Genderless",
    "Keldeo - Resolute - Genderless",
    "Meloetta - Genderless",
    "Genesect - Genderless"
];

export const kalosPokemon = [
    "Chespin - Male",
    "Chespin - Female",
    "Quilladin - Male",
    "Quilladin - Female",
    "Chesnaught - Male",
    "Chesnaught - Female",
    "Fennekin - Male",
    "Fennekin - Female",
    "Braixen - Male",
    "Braixen - Female",
    "Delphox - Male",
    "Delphox - Female",
    "Froakie - Male",
    "Froakie - Female",
    "Frogadier - Male",
    "Frogadier - Female",
    "Greninja - Male",
    "Greninja - Female",
    "Bunnelby - Male",
    "Bunnelby - Female",
    "Diggersby - Male",
    "Diggersby - Female",
    "Fletchling - Male",
    "Fletchling - Female",
    "Fletchinder - Male",
    "Fletchinder - Female",
    "Talonflame - Male",
    "Talonflame - Female",
    "Scatterbug - Male",
    "Scatterbug - Female",
    "Spewpa - Male",
    "Spewpa - Female",
    "Vivillon - Blank - Male",
    "Vivillon - Blank - Female",
    "Vivillon - Polar - Male",
    "Vivillon - Polar - Female",
    "Vivillon - Tundra - Male",
    "Vivillon - Tundra - Female",
    "Vivillon - Continental - Male",
    "Vivillon - Continental - Female",
    "Vivillon - Garden - Male",
    "Vivillon - Garden - Female",
    "Vivillon - Elegant - Male",
    "Vivillon - Elegant - Female",
    "Vivillon - Meadow - Male",
    "Vivillon - Meadow - Female",
    "Vivillon - Modern - Male",
    "Vivillon - Modern - Female",
    "Vivillon - Marine - Male",
    "Vivillon - Marine - Female",
    "Vivillon - Archipelago - Male",
    "Vivillon - Archipelago - Female",
    "Vivillon - High Plains - Male",
    "Vivillon - High Plains - Female",
    "Vivillon - Sandstorm - Male",
    "Vivillon - Sandstorm - Female",
    "Vivillon - River - Male",
    "Vivillon - River - Female",
    "Vivillon - Monsoon - Male",
    "Vivillon - Monsoon - Female",
    "Vivillon - Savanna - Male",
    "Vivillon - Savanna - Female",
    "Vivillon - Sun - Male",
    "Vivillon - Sun - Female",
    "Vivillon - Ocean - Male",
    "Vivillon - Ocean - Female",
    "Vivillon - Jungle - Male",
    "Vivillon - Jungle - Female",
    "Vivillon - Fancy - Male",
    "Vivillon - Fancy - Female",
    "Vivillon - Pokéball - Male",
    "Vivillon - Pokéball - Female",
    "Litleo - Male",
    "Litleo - Female",
    "Pyroar - Male",
    "Pyroar - Female",
    "Flabébé - Red - Female",
    "Flabébé - Orange - Female",
    "Flabébé - Yellow - Female",
    "Flabébé - Blue - Female",
    "Flabébé - White - Female",
    "Floette - Red - Female",
    "Floette - Orange - Female",
    "Floette - Yellow - Female",
    "Floette - Blue - Female",
    "Floette - White - Female",
    "Florges - Red - Female",
    "Florges - Orange - Female",
    "Florges - Yellow - Female",
    "Florges - Blue - Female",
    "Florges - White - Female",
    "Skiddo - Male",
    "Skiddo - Female",
    "Gogoat - Male",
    "Gogoat - Female",
    "Pancham - Male",
    "Pancham - Female",
    "Pangoro - Male",
    "Pangoro - Female",
    "Furfrou - Normal - Male",
    "Furfrou - Normal - Female",
    "Furfrou - Heart Trim - Male",
    "Furfrou - Heart Trim - Female",
    "Furfrou - Star Trim - Male",
    "Furfrou - Star Trim - Female",
    "Furfrou - Diamond Trim - Male",
    "Furfrou - Diamond Trim - Female",
    "Furfrou - Debutante Trim - Male",
    "Furfrou - Debutante Trim - Female",
    "Furfrou - Matron Trim - Male",
    "Furfrou - Matron Trim - Female",
    "Furfrou - Dandy Trim - Male",
    "Furfrou - Dandy Trim - Female",
    "Furfrou - La Reine Trim - Male",
    "Furfrou - La Reine Trim - Female",
    "Furfrou - Kabuki Trim - Male",
    "Furfrou - Kabuki Trim - Female",
    "Furfrou - Pharaoh Trim - Male",
    "Furfrou - Pharaoh Trim - Female",
    "Espurr - Male",
    "Espurr - Female",
    "Meowstic - Male",
    "Meowstic - Female",
    "Honedge - Male",
    "Honedge - Female",
    "Doublade - Male",
    "Doublade - Female",
    "Aegislash - Male",
    "Aegislash - Female",
    "Spritzee - Male",
    "Spritzee - Female",
    "Aromatisse - Male",
    "Aromatisse - Female",
    "Swirlix - Male",
    "Swirlix - Female",
    "Slurpuff - Male",
    "Slurpuff - Female",
    "Inkay - Male",
    "Inkay - Female",
    "Malamar - Male",
    "Malamar - Female",
    "Binacle - Male",
    "Binacle - Female",
    "Barbaracle - Male",
    "Barbaracle - Female",
    "Skrelp - Male",
    "Skrelp - Female",
    "Dragalge - Male",
    "Dragalge - Female",
    "Clauncher - Male",
    "Clauncher - Female",
    "Clawitzer - Male",
    "Clawitzer - Female",
    "Helioptile - Male",
    "Helioptile - Female",
    "Heliolisk - Male",
    "Heliolisk - Female",
    "Tyrunt - Male",
    "Tyrunt - Female",
    "Tyrantrum - Male",
    "Tyrantrum - Female",
    "Amaura - Male",
    "Amaura - Female",
    "Aurorus - Male",
    "Aurorus - Female",
    "Sylveon - Male",
    "Sylveon - Female",
    "Hawlucha - Male",
    "Hawlucha - Female",
    "Dedenne - Male",
    "Dedenne - Female",
    "Carbink - Genderless",
    "Goomy - Male",
    "Goomy - Female",
    "Sliggoo - Male",
    "Sliggoo - Female",
    "Goodra - Male",
    "Goodra - Female",
    "Klefki - Male",
    "Klefki - Female",
    "Phantump - Male",
    "Phantump - Female",
    "Trevenant - Male",
    "Trevenant - Female",
    "Pumpkaboo - Small - Male",
    "Pumpkaboo - Small - Female",
    "Pumpkaboo - Medium - Male",
    "Pumpkaboo - Medium - Female",
    "Pumpkaboo - Large - Male",
    "Pumpkaboo - Large - Female",
    "Pumpkaboo - Super - Male",
    "Pumpkaboo - Super - Female",
    "Gourgeist - Small - Male",
    "Gourgeist - Small - Female",
    "Gourgeist - Medium - Male",
    "Gourgeist - Medium - Female",
    "Gourgeist - Large - Male",
    "Gourgeist - Large - Female",
    "Gourgeist - Super - Male",
    "Gourgeist - Super - Female",
    "Bergmite - Male",
    "Bergmite - Female",
    "Avalugg - Male",
    "Avalugg - Female",
    "Noibat - Male",
    "Noibat - Female",
    "Noivern - Male",
    "Noivern - Female",
    "Xerneas - Genderless",
    "Yveltal - Genderless",
    "Zygarde - Genderless",
    "Diancie - Genderless",
    "Hoopa - Genderless",
    "Hoopa - Unbound - Genderless",
    "Volcanion - Genderless"
];

export const alolaPokemon = [
    "Rowlet - Male",
    "Rowlet - Female",
    "Dartrix - Male",
    "Dartrix - Female",
    "Decidueye - Male",
    "Decidueye - Female",
    "Litten - Male",
    "Litten - Female",
    "Torracat - Male",
    "Torracat - Female",
    "Incineroar - Male",
    "Incineroar - Female",
    "Popplio - Male",
    "Popplio - Female",
    "Brionne - Male",
    "Brionne - Female",
    "Primarina - Male",
    "Primarina - Female",
    "Pikipek - Male",
    "Pikipek - Female",
    "Trumbeak - Male",
    "Trumbeak - Female",
    "Toucannon - Male",
    "Toucannon - Female",
    "Yungoos - Male",
    "Yungoos - Female",
    "Gumshoos - Male",
    "Gumshoos - Female",
    "Grubbin - Male",
    "Grubbin - Female",
    "Charjabug - Male",
    "Charjabug - Female",
    "Vikavolt - Male",
    "Vikavolt - Female",
    "Crabrawler - Male",
    "Crabrawler - Female",
    "Crabominable - Male",
    "Crabominable - Female",
    "Oricorio - Baile - Male",
    "Oricorio - Baile - Female",
    "Oricorio - Pom-Pom - Male",
    "Oricorio - Pom-Pom - Female",
    "Oricorio - Pa'u - Male",
    "Oricorio - Pa'u - Female",
    "Oricorio - Sensu - Male",
    "Oricorio - Sensu - Female",
    "Cutiefly - Male",
    "Cutiefly - Female",
    "Ribombee - Male",
    "Ribombee - Female",
    "Rockruff - Male",
    "Rockruff - Female",
    "Lycanroc - Midday - Male",
    "Lycanroc - Midday - Female",
    "Lycanroc - Dusk - Male",
    "Lycanroc - Dusk - Female",
    "Lycanroc - Midnight - Male",
    "Lycanroc - Midnight - Female",
    "Wishiwashi - Male",
    "Wishiwashi - Female",
    "Mareanie - Male",
    "Mareanie - Female",
    "Toxapex - Male",
    "Toxapex - Female",
    "Mudbray - Male",
    "Mudbray - Female",
    "Mudsdale - Male",
    "Mudsdale - Female",
    "Dewpider - Male",
    "Dewpider - Female",
    "Araquanid - Male",
    "Araquanid - Female",
    "Fomantis - Male",
    "Fomantis - Female",
    "Lurantis - Male",
    "Lurantis - Female",
    "Morelull - Male",
    "Morelull - Female",
    "Shiinotic - Male",
    "Shiinotic - Female",
    "Salandit - Male",
    "Salandit - Female",
    "Salazzle - Female",
    "Stufful - Male",
    "Stufful - Female",
    "Bewear - Male",
    "Bewear - Female",
    "Bounsweet - Female",
    "Steenee - Female",
    "Tsareena - Female",
    "Comfey - Male",
    "Comfey - Female",
    "Oranguru - Male",
    "Oranguru - Female",
    "Passimian - Male",
    "Passimian - Female",
    "Wimpod - Male",
    "Wimpod - Female",
    "Golisopod - Male",
    "Golisopod - Female",
    "Sandygast - Male",
    "Sandygast - Female",
    "Palossand - Male",
    "Palossand - Female",
    "Pyukumuku - Male",
    "Pyukumuku - Female",
    "Type: Null - Genderless",
    "Silvally - Genderless",
    "Minior - Red - Genderless",
    "Minior - Orange - Genderless",
    "Minior - Yellow - Genderless",
    "Minior - Green - Genderless",
    "Minior - Blue - Genderless",
    "Minior - Indigo - Genderless",
    "Minior - Violet - Genderless",
    "Komala - Male",
    "Komala - Female",
    "Turtonator - Male",
    "Turtonator - Female",
    "Togedemaru - Male",
    "Togedemaru - Female",
    "Mimikyu - Male",
    "Mimikyu - Female",
    "Bruxish - Male",
    "Bruxish - Female",
    "Drampa - Male",
    "Drampa - Female",
    "Dhelmise - Genderless",
    "Jangmo-o - Male",
    "Jangmo-o - Female",
    "Hakamo-o - Male",
    "Hakamo-o - Female",
    "Kommo-o - Male",
    "Kommo-o - Female",
    "Tapu Koko - Genderless",
    "Tapu Lele - Genderless",
    "Tapu Bulu - Genderless",
    "Tapu Fini - Genderless",
    "Cosmog - Genderless",
    "Cosmoem - Genderless",
    "Solgaleo - Genderless",
    "Lunala - Genderless",
    "Nihilego - Genderless",
    "Buzzwole - Genderless",
    "Pheromosa - Genderless",
    "Xurkitree - Genderless",
    "Celesteela - Genderless",
    "Kartana - Genderless",
    "Guzzlord - Genderless",
    "Necrozma - Genderless",
    "Magearna - Genderless",
    "Magearna - Original Color - Genderless",
    "Marshadow - Genderless",
    "Poipole - Genderless",
    "Naganadel - Genderless",
    "Stakataka - Genderless",
    "Blacephalon - Genderless",
    "Zeraora - Genderless",
    "Meltan - Genderless",
    "Melmetal - Genderless",
    "Alolan Rattata - Male",
    "Alolan Rattata - Female",
    "Alolan Raticate - Male",
    "Alolan Raticate - Female",
    "Alolan Raichu - Male",
    "Alolan Raichu - Female",
    "Alolan Sandshrew - Male",
    "Alolan Sandshrew - Female",
    "Alolan Sandslash - Male",
    "Alolan Sandslash - Female",
    "Alolan Vulpix - Male",
    "Alolan Vulpix - Female",
    "Alolan Ninetails - Male",
    "Alolan Ninetails - Female",
    "Alolan Diglett - Male",
    "Alolan Diglett - Female",
    "Alolan Dugtrio - Male",
    "Alolan Dugtrio - Female",
    "Alolan Meowth - Male",
    "Alolan Meowth - Female",
    "Alolan Persian - Male",
    "Alolan Persian - Female",
    "Alolan Geodude - Male",
    "Alolan Geodude - Female",
    "Alolan Graveler - Male",
    "Alolan Graveler - Female",
    "Alolan Golem - Male",
    "Alolan Golem - Female",
    "Alolan Grimer - Male",
    "Alolan Grimer - Female",
    "Alolan Muk - Male",
    "Alolan Muk - Female",
    "Alolan Exeggutor - Male",
    "Alolan Exeggutor - Female",
    "Alolan Marowak - Male",
    "Alolan Marowak - Female",
    "Zygarde - 10 Percent - Genderless"
];

export const galarPokemon = [
    "Grookey - Male",
    "Grookey - Female",
    "Thwackey - Male",
    "Thwackey - Female",
    "Rillaboom - Male",
    "Rillaboom - Female",
    "Scorbunny - Male",
    "Scorbunny - Female",
    "Raboot - Male",
    "Raboot - Female",
    "Cinderace - Male",
    "Cinderace - Female",
    "Sobble - Male",
    "Sobble - Female",
    "Drizzile - Male",
    "Drizzile - Female",
    "Inteleon - Male",
    "Inteleon - Female",
    "Skwovet - Male",
    "Skwovet - Female",
    "Greedent - Male",
    "Greedent - Female",
    "Rookidee - Male",
    "Rookidee - Female",
    "Corvisquire - Male",
    "Corvisquire - Female",
    "Corviknight - Male",
    "Corviknight - Female",
    "Blipbug - Male",
    "Blipbug - Female",
    "Dottler - Male",
    "Dottler - Female",
    "Orbeetle - Male",
    "Orbeetle - Female",
    "Nickit - Male",
    "Nickit - Female",
    "Thievul - Male",
    "Thievul - Female",
    "Gossifleur - Male",
    "Gossifleur - Female",
    "Eldegoss - Male",
    "Eldegoss - Female",
    "Wooloo - Male",
    "Wooloo - Female",
    "Dubwool - Male",
    "Dubwool - Female",
    "Chewtle - Male",
    "Chewtle - Female",
    "Drednaw - Male",
    "Drednaw - Female",
    "Yamper - Male",
    "Yamper - Female",
    "Boltund - Male",
    "Boltund - Female",
    "Rolycoly - Male",
    "Rolycoly - Female",
    "Carkol - Male",
    "Carkol - Female",
    "Coalossal - Male",
    "Coalossal - Female",
    "Applin - Male",
    "Applin - Female",
    "Flapple - Male",
    "Flapple - Female",
    "Appletun - Male",
    "Appletun - Female",
    "Silicobra - Male",
    "Silicobra - Female",
    "Sandaconda - Male",
    "Sandaconda - Female",
    "Cramorant - Male",
    "Cramorant - Female",
    "Arrokuda - Male",
    "Arrokuda - Female",
    "Barraskewda - Male",
    "Barraskewda - Female",
    "Toxel - Male",
    "Toxel - Female",
    "Toxtricity - Amped - Male",
    "Toxtricity - Amped - Female",
    "Toxtricity - Low Key - Male",
    "Toxtricity - Low Key - Female",
    "Sizzlipede - Male",
    "Sizzlipede - Female",
    "Centiskorch - Male",
    "Centiskorch - Female",
    "Clobbopus - Male",
    "Clobbopus - Female",
    "Grapploct - Male",
    "Grapploct - Female",
    "Sinistea - Phony - Genderless",
    "Sinistea - Antique - Genderless",
    "Polteageist - Phony - Genderless",
    "Polteageist - Antique - Genderless",
    "Hatenna - Female",
    "Hattrem - Female",
    "Hatterene - Female",
    "Impidimp - Male",
    "Morgrem - Male",
    "Grimmsnarl - Male",
    "Obstagoon - Male",
    "Obstagoon - Female",
    "Perrserker - Male",
    "Perrserker - Female",
    "Cursola - Male",
    "Cursola - Female",
    "Sirfetch'd - Male",
    "Sirfetch'd - Female",
    "Mr. Rime - Male",
    "Mr. Rime - Female",
    "Runerigus - Male",
    "Runerigus - Female",
    "Milcery - Female",
    "Alcremie - Vanilla Cream - Strawberry Sweet - Female",
    "Alcremie - Vanilla Cream - Berry Sweet - Female",
    "Alcremie - Vanilla Cream - Love Sweet - Female",
    "Alcremie - Vanilla Cream - Star Sweet - Female",
    "Alcremie - Vanilla Cream - Clover Sweet - Female",
    "Alcremie - Vanilla Cream - Flower Sweet - Female",
    "Alcremie - Vanilla Cream - Ribbon Sweet - Female",
    "Alcremie - Ruby Cream - Strawberry Sweet - Female",
    "Alcremie - Ruby Cream - Berry Sweet - Female",
    "Alcremie - Ruby Cream - Love Sweet - Female",
    "Alcremie - Ruby Cream - Star Sweet - Female",
    "Alcremie - Ruby Cream - Clover Sweet - Female",
    "Alcremie - Ruby Cream - Flower Sweet - Female",
    "Alcremie - Ruby Cream - Ribbon Sweet - Female",
    "Alcremie - Matcha Cream - Strawberry Sweet - Female",
    "Alcremie - Matcha Cream - Berry Sweet - Female",
    "Alcremie - Matcha Cream - Love Sweet - Female",
    "Alcremie - Matcha Cream - Star Sweet - Female",
    "Alcremie - Matcha Cream - Clover Sweet - Female",
    "Alcremie - Matcha Cream - Flower Sweet - Female",
    "Alcremie - Matcha Cream - Ribbon Sweet - Female",
    "Alcremie - Mint Cream - Strawberry Sweet - Female",
    "Alcremie - Mint Cream - Berry Sweet - Female",
    "Alcremie - Mint Cream - Love Sweet - Female",
    "Alcremie - Mint Cream - Star Sweet - Female",
    "Alcremie - Mint Cream - Clover Sweet - Female",
    "Alcremie - Mint Cream - Flower Sweet - Female",
    "Alcremie - Mint Cream - Ribbon Sweet - Female",
    "Alcremie - Lemon Cream - Strawberry Sweet - Female",
    "Alcremie - Lemon Cream - Berry Sweet - Female",
    "Alcremie - Lemon Cream - Love Sweet - Female",
    "Alcremie - Lemon Cream - Star Sweet - Female",
    "Alcremie - Lemon Cream - Clover Sweet - Female",
    "Alcremie - Lemon Cream - Flower Sweet - Female",
    "Alcremie - Lemon Cream - Ribbon Sweet - Female",
    "Alcremie - Salted Cream - Strawberry Sweet - Female",
    "Alcremie - Salted Cream - Berry Sweet - Female",
    "Alcremie - Salted Cream - Love Sweet - Female",
    "Alcremie - Salted Cream - Star Sweet - Female",
    "Alcremie - Salted Cream - Clover Sweet - Female",
    "Alcremie - Salted Cream - Flower Sweet - Female",
    "Alcremie - Salted Cream - Ribbon Sweet - Female",
    "Alcremie - Ruby Swirl - Strawberry Sweet - Female",
    "Alcremie - Ruby Swirl - Berry Sweet - Female",
    "Alcremie - Ruby Swirl - Love Sweet - Female",
    "Alcremie - Ruby Swirl - Star Sweet - Female",
    "Alcremie - Ruby Swirl - Clover Sweet - Female",
    "Alcremie - Ruby Swirl - Flower Sweet - Female",
    "Alcremie - Ruby Swirl - Ribbon Sweet - Female",
    "Alcremie - Caramel Swirl - Strawberry Sweet - Female",
    "Alcremie - Caramel Swirl - Berry Sweet - Female",
    "Alcremie - Caramel Swirl - Love Sweet - Female",
    "Alcremie - Caramel Swirl - Star Sweet - Female",
    "Alcremie - Caramel Swirl - Clover Sweet - Female",
    "Alcremie - Caramel Swirl - Flower Sweet - Female",
    "Alcremie - Caramel Swirl - Ribbon Sweet - Female",
    "Alcremie - Rainbow Swirl - Strawberry Sweet - Female",
    "Alcremie - Rainbow Swirl - Berry Sweet - Female",
    "Alcremie - Rainbow Swirl - Love Sweet - Female",
    "Alcremie - Rainbow Swirl - Star Sweet - Female",
    "Alcremie - Rainbow Swirl - Clover Sweet - Female",
    "Alcremie - Rainbow Swirl - Flower Sweet - Female",
    "Alcremie - Rainbow Swirl - Ribbon Sweet - Female",
    "Falinks - Genderless",
    "Pincurchin - Male",
    "Pincurchin - Female",
    "Snom - Male",
    "Snom - Female",
    "Frosmoth - Male",
    "Frosmoth - Female",
    "Stonjourner - Male",
    "Stonjourner - Female",
    "Eiscue - Male",
    "Eiscue - Female",
    "Indeedee - Male",
    "Indeedee - Female",
    "Morpeko - Male",
    "Morpeko - Female",
    "Cufant - Male",
    "Cufant - Female",
    "Copperajah - Male",
    "Copperajah - Female",
    "Dracozolt - Genderless",
    "Arctozolt - Genderless",
    "Dracovish - Genderless",
    "Arctovish - Genderless",
    "Duraludon - Male",
    "Duraludon - Female",
    "Dreepy - Male",
    "Dreepy - Female",
    "Drakloak - Male",
    "Drakloak - Female",
    "Dragapult - Male",
    "Dragapult - Female",
    "Zacian - Genderless",
    "Zamazenta - Genderless",
    "Eternatus - Genderless",
    "Kubfu - Male",
    "Kubfu - Female",
    "Urshifu - Single Strike - Male",
    "Urshifu - Single Strike - Female",
    "Urshifu - Rapid Strike - Male",
    "Urshifu - Rapid Strike - Female",
    "Zarude - Genderless",
    "Zarude - Dada - Genderless",
    "Regieleki - Genderless",
    "Regidrago - Genderless",
    "Glastrier - Genderless",
    "Spectrier - Genderless",
    "Calyrex - Genderless",
    "Galarian Meowth - Male",
    "Galarian Meowth - Female",
    "Galarian Ponyta - Male",
    "Galarian Ponyta - Female",
    "Galarian Rapidash - Male",
    "Galarian Rapidash - Female",
    "Galarian Slowpoke - Male",
    "Galarian Slowpoke - Female",
    "Galarian Slowbro - Male",
    "Galarian Slowbro - Female",
    "Galarian Sirfetch'd - Male",
    "Galarian Sirfetch'd - Female",
    "Galarian Weezing - Male",
    "Galarian Weezing - Female",
    "Galarian Mr. Mime - Male",
    "Galarian Mr. Mime - Female",
    "Galarian Articuno - Genderless",
    "Galarian Moltres - Genderless",
    "Galarian Zapdos - Genderless",
    "Galarian Slowking - Male",
    "Galarian Slowking - Female",
    "Galarian Corsola - Male",
    "Galarian Corsola - Female",
    "Galarian Zigzagoon - Male",
    "Galarian Zigzagoon - Female",
    "Galarian Linoone - Male",
    "Galarian Linoone - Female",
    "Galarian Darumaka - Male",
    "Galarian Darumaka - Female",
    "Galarian Darmanitan - Male",
    "Galarian Darmanitan - Female",
    "Galarian Yamask - Male",
    "Galarian Yamask - Female",
    "Galarian Stunfisk - Male",
    "Galarian Stunfisk - Female",
];

export const hisuiPokemon = [
    "Wyrdeer - Male",
    "Wyrdeer - Female",
    "Kleavor - Male",
    "Kleavor - Female",
    "Ursaluna - Male",
    "Ursaluna - Female",
    "Basculegion - Male",
    "Basculegion - Female",
    "Sneasler - Male",
    "Sneasler - Female",
    "Overqwil - Male",
    "Overqwil - Female",
    "Enamorus - Female",
    "Enamorus - Therian - Female",
    "Hisuian Growlithe - Male",
    "Hisuian Growlithe - Female",
    "Hisuian Arcanine - Male",
    "Hisuian Arcanine - Female",
    "Hisuian Voltorb - Male",
    "Hisuian Voltorb - Female",
    "Hisuian Electrode - Male",
    "Hisuian Electrode - Female",
    "Hisuian Typhlosion - Male",
    "Hisuian Typhlosion - Female",
    "Hisuian Qwilfish - Male",
    "Hisuian Qwilfish - Female",
    "Hisuian Sneasel - Male",
    "Hisuian Sneasel - Female",
    "Hisuian Samurott - Male",
    "Hisuian Samurott - Female",
    "Hisuian Lilligant - Female",
    "Hisuian Basculin - White",
    "Hisuian Zorua - Male",
    "Hisuian Zorua - Female",
    "Hisuian Zoroark - Male",
    "Hisuian Zoroark - Female",
    "Hisuian Braviary - Male",
    "Hisuian Sliggoo - Male",
    "Hisuian Sliggoo - Female",
    "Hisuian Goodra - Male",
    "Hisuian Goodra - Female",
    "Hisuian Avalugg - Male",
    "Hisuian Avalugg - Female",
    "Hisuian Decidueye - Male",
    "Hisuian Decidueye - Female"
];

export const paldeaPokemon = [
    "Sprigatito - Male",
    "Sprigatito - Female",
    "Floragato - Male",
    "Floragato - Female",
    "Meowscarada - Male",
    "Meowscarada - Female",
    "Fuecoco - Male",
    "Fuecoco - Female",
    "Crocalor - Male",
    "Crocalor - Female",
    "Skeledirge - Male",
    "Skeledirge - Female",
    "Quaxly - Male",
    "Quaxly - Female",
    "Quaxwell - Male",
    "Quaxwell - Female",
    "Quaquaval - Male",
    "Quaquaval - Female",
    "Lechonk - Male",
    "Lechonk - Female",
    "Oinkologne - Male",
    "Oinkologne - Female",
    "Tarountula - Male",
    "Tarountula - Female",
    "Spidops - Male",
    "Spidops - Female",
    "Nymble - Male",
    "Nymble - Female",
    "Lokix - Male",
    "Lokix - Female",
    "Pawmi - Male",
    "Pawmi - Female",
    "Pawmo - Male",
    "Pawmo - Female",
    "Pawmot - Male",
    "Pawmot - Female",
    "Tandemaus - Genderless",
    "Maushold - Three - Genderless",
    "Maushold - Four - Genderless",
    "Fidough - Male",
    "Fidough - Female",
    "Dachsbun - Male",
    "Dachsbun - Female",
    "Smoliv - Male",
    "Smoliv - Female",
    "Dolliv - Male",
    "Dolliv - Female",
    "Arboliva - Male",
    "Arboliva - Female",
    "Squawkabilly - Green - Male",
    "Squawkabilly - Green - Female",
    "Squawkabilly - Blue - Male",
    "Squawkabilly - Blue - Female",
    "Squawkabilly - Yellow - Male",
    "Squawkabilly - Yellow - Female",
    "Squawkabilly - White - Male",
    "Squawkabilly - White - Female",
    "Nacli - Male",
    "Nacli - Female",
    "Naclstack - Male",
    "Naclstack - Female",
    "Garganacl - Male",
    "Garganacl - Female",
    "Charcadet - Male",
    "Charcadet - Female",
    "Armarouge - Male",
    "Armarouge - Female",
    "Ceruledge - Male",
    "Ceruledge - Female",
    "Tadbulb - Male",
    "Tadbulb - Female",
    "Bellibolt - Male",
    "Bellibolt - Female",
    "Wattrel - Male",
    "Wattrel - Female",
    "Kilowattrel - Male",
    "Kilowattrel - Female",
    "Maschiff - Male",
    "Maschiff - Female",
    "Mabosstiff - Male",
    "Mabosstiff - Female",
    "Shroodle - Male",
    "Shroodle - Female",
    "Grafaiai - Male",
    "Grafaiai - Female",
    "Bramblin - Male",
    "Bramblin - Female",
    "Brambleghast - Male",
    "Brambleghast - Female",
    "Toedscool - Male",
    "Toedscool - Female",
    "Toedscruel - Male",
    "Toedscruel - Female",
    "Klawf - Male",
    "Klawf - Female",
    "Capsakid - Male",
    "Capsakid - Female",
    "Scovillain - Male",
    "Scovillain - Female",
    "Rellor - Male",
    "Rellor - Female",
    "Rabsca - Male",
    "Rabsca - Female",
    "Flittle - Male",
    "Flittle - Female",
    "Espathra - Male",
    "Espathra - Female",
    "Tinkatink - Female",
    "Tinkatuff - Female",
    "Tinkaton - Female",
    "Wiglett - Male",
    "Wiglett - Female",
    "Wugtrio - Male",
    "Wugtrio - Female",
    "Bombirdier - Male",
    "Bombirdier - Female",
    "Finizen - Male",
    "Finizen - Female",
    "Palafin - Male",
    "Palafin - Female",
    "Varoom - Male",
    "Varoom - Female",
    "Revavroom - Male",
    "Revavroom - Female",
    "Cyclizar - Male",
    "Cyclizar - Female",
    "Orthworm - Male",
    "Orthworm - Female",
    "Glimmet - Male",
    "Glimmet - Female",
    "Glimmora - Male",
    "Glimmora - Female",
    "Greavard - Male",
    "Greavard - Female",
    "Houndstone - Male",
    "Houndstone - Female",
    "Flamigo - Male",
    "Flamigo - Female",
    "Cetoddle - Male",
    "Cetoddle - Female",
    "Cetitan - Male",
    "Cetitan - Female",
    "Veluza - Male",
    "Veluza - Female",
    "Dondozo - Male",
    "Dondozo - Female",
    "Tatsugiri - Curly - Male",
    "Tatsugiri - Curly - Female",
    "Tatsugiri - Droopy - Male",
    "Tatsugiri - Droopy - Female",
    "Tatsugiri - Stretchy - Male",
    "Tatsugiri - Stretchy - Female",
    "Annihilape - Male",
    "Annihilape - Female",
    "Clodsire - Male",
    "Clodsire - Female",
    "Farigiraf - Male",
    "Farigiraf - Female",
    "Dudunsparce - Two Segment - Male",
    "Dudunsparce - Two Segment - Female",
    "Dudunsparce - Three Segment - Male",
    "Dudunsparce - Three Segment - Female",
    "Kingambit - Male",
    "Kingambit - Female",
    "Great Tusk - Genderless",
    "Scream Tail - Genderless",
    "Brute Bonnet - Genderless",
    "Flutter Mane - Genderless",
    "Slither Wing - Genderless",
    "Sandy Shocks - Genderless",
    "Iron Treads - Genderless",
    "Iron Bundle - Genderless",
    "Iron Hands - Genderless",
    "Iron Jugulis - Genderless",
    "Iron Moth - Genderless",
    "Iron Thorns - Genderless",
    "Frigibax - Male",
    "Frigibax - Female",
    "Arctibax - Male",
    "Arctibax - Female",
    "Baxcalibur - Male",
    "Baxcalibur - Female",
    "Gimmighoul - Genderless",
    "Gimmighoul - Roaming - Genderless",
    "Gholdengo - Genderless",
    "Wo-Chien - Genderless",
    "Chien-Pao - Genderless",
    "Ting-Lu - Genderless",
    "Chi-Yu - Genderless",
    "Roaring Moon - Genderless",
    "Iron Valiant - Genderless",
    "Koraidon - Genderless",
    "Miraidon - Genderless",
    "Walking Wake - Genderless",
    "Iron Leaves - Genderless",
    "Dipplin - Male",
    "Dipplin - Female",
    "Poltchageist - Counterfeit - Genderless",
    "Poltchageist - Artisan - Genderless",
    "Sinistcha - Counterfeit - Genderless",
    "Sinistcha - Artisan - Genderless",
    "Okidogi - Male",
    "Munkidori - Male",
    "Fezandipiti - Male",
    "Ogerpon - Female",
    "Archaludon - Male",
    "Archaludon - Female",
    "Hydrapple - Male",
    "Hydrapple - Female",
    "Gouging Fire - Genderless",
    "Raging Bolt - Genderless",
    "Iron Boulder - Genderless",
    "Iron Crown - Genderless",
    "Terapagos - Male",
    "Terapagos - Female",
    "Pecharunt - Genderless",
    "Ursaluna - Blood Moon - Male",
    "Ursaluna - Blood Moon - Female",
    "Paldean - Taurus - Male",
    "Paldean - Taurus Blaze - Male",
    "Paldean - Taurus Aqua - Male",
    "Paldean - Wooper - Male",
    "Paldean - Wooper - Female"
];